### ISSUE TITLE
Cannot find module lib/prefetch

### ISSUE THREAD

**Issue by fernando-deka** [fgnass/react-api-query#1]
Error: Cannot find module '.../node_modules/react-api-query/lib/prefetch' imported from .../node_modules/react-api-query/lib/index.js

I found a fix which is to change the export line on the index file from:
`export { prefetching } from "./prefetch";`
to:
`export { prefetching } from "./prefetch.js";`

**Comment by fgnass** [comment]
Thanks for your report! I published a fix as react-api-query@2.2.4
